### ISSUE TITLE
Issue with dowload in local

### ISSUE THREAD

**Issue by Lucifer-00007** [meowtec/audio-cutter#13]
![image](https://user-images.githubusercontent.com/57388389/200136240-b8157ab6-9a07-47f7-a5ae-9ee57f33700b.png)

I run this code locally and i cropped a mp3 but after crop when i try to download it, I am not able to do so...

Actually when i click on the download button their is an infinite loader going on continuously!!

@helmarluiz @meowtec  can you help me fix this issue??

**Comment by meowtec** [comment]
What's your browser and the version?
Did you try in latest chrome?

**Comment by Lucifer-00007** [comment]
> Firefox  v106.0.5 which is the latest version!
I am using windows system!

I have also tried to run this code on latest chrome browser but still facing the same issue!

**Comment by meowtec** [comment]
> > Firefox  v106.0.5 which is the latest version!
> > I am using windows system!
> 
> I have also tried to run this code on latest chrome browser but still facing the same issue!

Could you provide your audio file?

**Comment by Lucifer-00007** [comment]
> > > Firefox  v106.0.5 which is the latest version!
> > > I am using windows system!
> > 
> > 
> > I have also tried to run this code on latest chrome browser but still facing the same issue!
> 
> Could you provide your audio file?

[music.zip](https://github.com/meowtec/audio-cutter/files/9959458/music.zip)
This is the audio file

**Comment by meowtec** [comment]
@Lucifer-00007 This should have been fixed. Thanks!

**Comment by timgyaki** [comment]
Hi I also have the same problem, it still doesn`t work for me.
The example in the readme works for me, but if I try to download my cutted file on local it doesn`t work.

@meowtec @helmarluiz can you help me fix this problem?

This is the error:
![image](https://user-images.githubusercontent.com/118278729/201950982-f35d5821-e940-48e1-b2b3-d291b82aa0b2.png)

**Comment by meowtec** [comment]
@timgyaki 
Which branch are you checking in? Did you forgot `git pull`?
